version: '3.8'

services:

  db:
    image: postgres
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: db-adminer
    restart: always
    ports:
      - "9001:8080"
