# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/michalmo/ZPR/flashcardapp

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/michalmo/ZPR/flashcardapp

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michalmo/ZPR/flashcardapp/CMakeFiles /home/michalmo/ZPR/flashcardapp//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/michalmo/ZPR/flashcardapp/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FlashcardApp

# Build rule for target.
FlashcardApp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlashcardApp
.PHONY : FlashcardApp

# fast build rule for target.
FlashcardApp/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/build
.PHONY : FlashcardApp/fast

#=============================================================================
# Target rules for targets named FlashcardApp_autogen

# Build rule for target.
FlashcardApp_autogen: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 FlashcardApp_autogen
.PHONY : FlashcardApp_autogen

# fast build rule for target.
FlashcardApp_autogen/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp_autogen.dir/build.make CMakeFiles/FlashcardApp_autogen.dir/build
.PHONY : FlashcardApp_autogen/fast

FlashcardApp_autogen/mocs_compilation.o: FlashcardApp_autogen/mocs_compilation.cpp.o
.PHONY : FlashcardApp_autogen/mocs_compilation.o

# target to build an object file
FlashcardApp_autogen/mocs_compilation.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/FlashcardApp_autogen/mocs_compilation.cpp.o
.PHONY : FlashcardApp_autogen/mocs_compilation.cpp.o

FlashcardApp_autogen/mocs_compilation.i: FlashcardApp_autogen/mocs_compilation.cpp.i
.PHONY : FlashcardApp_autogen/mocs_compilation.i

# target to preprocess a source file
FlashcardApp_autogen/mocs_compilation.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/FlashcardApp_autogen/mocs_compilation.cpp.i
.PHONY : FlashcardApp_autogen/mocs_compilation.cpp.i

FlashcardApp_autogen/mocs_compilation.s: FlashcardApp_autogen/mocs_compilation.cpp.s
.PHONY : FlashcardApp_autogen/mocs_compilation.s

# target to generate assembly for a file
FlashcardApp_autogen/mocs_compilation.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/FlashcardApp_autogen/mocs_compilation.cpp.s
.PHONY : FlashcardApp_autogen/mocs_compilation.cpp.s

src/flashcardmanagement/Flashcard.o: src/flashcardmanagement/Flashcard.cpp.o
.PHONY : src/flashcardmanagement/Flashcard.o

# target to build an object file
src/flashcardmanagement/Flashcard.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/flashcardmanagement/Flashcard.cpp.o
.PHONY : src/flashcardmanagement/Flashcard.cpp.o

src/flashcardmanagement/Flashcard.i: src/flashcardmanagement/Flashcard.cpp.i
.PHONY : src/flashcardmanagement/Flashcard.i

# target to preprocess a source file
src/flashcardmanagement/Flashcard.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/flashcardmanagement/Flashcard.cpp.i
.PHONY : src/flashcardmanagement/Flashcard.cpp.i

src/flashcardmanagement/Flashcard.s: src/flashcardmanagement/Flashcard.cpp.s
.PHONY : src/flashcardmanagement/Flashcard.s

# target to generate assembly for a file
src/flashcardmanagement/Flashcard.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/flashcardmanagement/Flashcard.cpp.s
.PHONY : src/flashcardmanagement/Flashcard.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/qt_ui/mainwindow.o: src/qt_ui/mainwindow.cpp.o
.PHONY : src/qt_ui/mainwindow.o

# target to build an object file
src/qt_ui/mainwindow.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/qt_ui/mainwindow.cpp.o
.PHONY : src/qt_ui/mainwindow.cpp.o

src/qt_ui/mainwindow.i: src/qt_ui/mainwindow.cpp.i
.PHONY : src/qt_ui/mainwindow.i

# target to preprocess a source file
src/qt_ui/mainwindow.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/qt_ui/mainwindow.cpp.i
.PHONY : src/qt_ui/mainwindow.cpp.i

src/qt_ui/mainwindow.s: src/qt_ui/mainwindow.cpp.s
.PHONY : src/qt_ui/mainwindow.s

# target to generate assembly for a file
src/qt_ui/mainwindow.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/FlashcardApp.dir/build.make CMakeFiles/FlashcardApp.dir/src/qt_ui/mainwindow.cpp.s
.PHONY : src/qt_ui/mainwindow.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... FlashcardApp_autogen"
	@echo "... FlashcardApp"
	@echo "... FlashcardApp_autogen/mocs_compilation.o"
	@echo "... FlashcardApp_autogen/mocs_compilation.i"
	@echo "... FlashcardApp_autogen/mocs_compilation.s"
	@echo "... src/flashcardmanagement/Flashcard.o"
	@echo "... src/flashcardmanagement/Flashcard.i"
	@echo "... src/flashcardmanagement/Flashcard.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/qt_ui/mainwindow.o"
	@echo "... src/qt_ui/mainwindow.i"
	@echo "... src/qt_ui/mainwindow.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

